// Copyright 2026 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | rgb565
//    output | graphics
//    input  | 2_4_g_icon_24x24.png

#pragma once

#include <stdint.h>

extern const uint32_t gfx_2_4_g_icon_24x24_length;
extern const uint8_t  gfx_2_4_g_icon_24x24[385];
