// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono2
//    unicode_glyphs | 
//    output         | graphics
//    input          | Iosevka-Medium-20.png

#pragma once

#include <stdint.h>

extern const uint32_t font_Iosevka_Medium_20_length;
extern const uint8_t  font_Iosevka_Medium_20[2415];
