// AUTO-GENERATED by res/mkraw.py --embed -- DO NOT EDIT.
// Source PNGs live in res/; regenerate with:  python3 res/mkraw.py --embed
//
// All pixel data is RGB565 in panel order. Fonts are monospace tile atlases subset to
// EMBED_CHARSET, stored as contiguous cell-sized glyphs in charset order, with their
// colours baked (COL_FG on COL_BG). See docs/LCD_FLASH_LAYER.md.

#pragma once
#include <stdint.h>

// RGB565 image tile, blit with lcd_draw_image().
typedef struct {
    uint16_t        w, h;
    const uint16_t *px;
} lcd_image_t;

// Monospace RGB565 glyph atlas: `charset` maps a character to its tile
// index, each tile cell_w*cell_h pixels. Colours are baked.
typedef struct {
    uint16_t        cell_w, cell_h;
    const char     *charset;
    const uint16_t *px;
} lcd_font_t;

extern const lcd_image_t img_2_4_g_icon_24x24;   // 24x24, 1152 bytes
extern const lcd_image_t img_apple_icon_24x24;   // 24x24, 1152 bytes
extern const lcd_image_t img_bluetooth_icon_24x24;   // 24x24, 1152 bytes
extern const lcd_image_t img_cable_icon_24x24;   // 24x24, 1152 bytes
extern const lcd_image_t img_sonixqmk;   // 128x128, 32768 bytes
extern const lcd_image_t img_windows_icon_24x24;   // 24x24, 1152 bytes

extern const lcd_font_t font_iosevka_medium_20;   // 13 glyphs @ 10x23, 5980 bytes
extern const lcd_font_t font_iosevka_regular_30;   // 13 glyphs @ 15x34, 13260 bytes
